// todo/svelte/my-app/src/App.svelte
<script>
	import { onMount } from 'svelte';
	let todos = [];
	let todoText = "";

	onMount(()=>{
		const existingTodos = localStorage.getItem("todos");
		todos = existingTodos? JSON.parse(existingTodos):[];
	});

	function addTodo(){
		todos = [...todos,todoText];
		localStorage.setItem("todos", JSON.stringify(todos)); 
	}
</script>;

<main>
	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>
	<form on:submit|preventDefault={addTodo}>
		<input bind:value={todoText}>
		<input type="submit" value="Add Todo">
	</form>
</main>

<style>
</style>

// todo/angular/my-app/src/app/app.component.ts
import { stringify } from '@angular/compiler/src/util';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-app';
  todos: string[] = [];
  todoText = "";

  ngOnInit(){
    const existingTodos = localStorage.getItem("todos");
    this.todos = existingTodos? JSON.parse(existingTodos):[];
  }

  addTodo(){
    this.todos.push(this.todoText);
    localStorage.setItem("todos",JSON.stringify(this.todos));
  }
}

<ul>
  <li *ngFor = "let todo of todos">{{todo}}</li>
</ul>
<form (ngSubmit) = "addTodo()">
  <input name="todoText" [(ngModel)]="todoText">
  <input type="submit" value="Add Todo">
</form>
