// todo/svelte/my-app/src/App.svelte
<script>
	import { onMount } from 'svelte';
	let todos = [];
	let todoText = "";

	onMount(()=>{
		const existingTodos = localStorage.getItem("todos");
		todos = existingTodos? JSON.parse(existingTodos):[];
	});

	function addTodo(){
		todos = [...todos,todoText];
		localStorage.setItem("todos", JSON.stringify(todos)); 
	}
</script>;

<main>
	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>
	<form on:submit|preventDefault={addTodo}>
		<input bind:value={todoText}>
		<input type="submit" value="Add Todo">
	</form>
</main>

<style>
</style>

// todo/solid/my-app/src/App.jsx
import {createSignal, onMount} from "solid-js";

function App() {
  let todoText;

  const [todos,setTodos] = createSignal([]);

  onMount(()=>{
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos?JSON.parse(existingTodos):[]);
    // localStorage.clear();
  });
  
  function addTodo(event){
    event.preventDefault();
    const next = [...todos(),todoText.value];
    setTodos(next);
    localStorage.setItem("todos",JSON.stringify(todos));
  }

  return (
    <div>
      <ul>
        {todos().map(todo=>(<li key={todo}>{todo}</li>))}
      </ul>
      <form onSubmit={addTodo}>
        <input type="text" ref={todoText}/>
        <input type="submit" value="Add Todo"/>
      </form>
    </div>
  );
}

export default App;
