// todo/react/my-app/src/App.js
import React, { useEffect, useRef, useState } from "react";
import './App.css';

function App() {
  // Setting the state and its function
  const [todos, setTodos] = useState([]);
  
  // Binding for input text field
  const todoText = useRef();

  useEffect(()=>{
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos?JSON.parse(existingTodos):[]);
  }, []);

  // Adding todo to the locat storage and the ui
  function addTodo(event){
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem("todos",JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos.map(todo => (<li key = {todo}>{todo}</li>))}
      </ul>
      <form onSubmit={addTodo}>
        <input ref = {todoText}/>
        <input type="submit" value="Add Todo"/>
      </form>
    </div>
  )
}

export default App;

// todo/solid/my-app/src/App.jsx
import {createSignal, onMount} from "solid-js";

function App() {
  let todoText;

  const [todos,setTodos] = createSignal([]);

  onMount(()=>{
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos?JSON.parse(existingTodos):[]);
    // localStorage.clear();
  });
  
  function addTodo(event){
    event.preventDefault();
    const next = [...todos(),todoText.value];
    setTodos(next);
    localStorage.setItem("todos",JSON.stringify(todos));
  }

  return (
    <div>
      <ul>
        {todos().map(todo=>(<li key={todo}>{todo}</li>))}
      </ul>
      <form onSubmit={addTodo}>
        <input type="text" ref={todoText}/>
        <input type="submit" value="Add Todo"/>
      </form>
    </div>
  );
}

export default App;
